---
- name: "dbconfig install"
  sudo: yes
  no_log: True
  debconf:
    name: "phpmyadmin"
    question: "phpmyadmin/dbconfig-install"
    value: "{{ phpmyadmin_dbconfig_install }}"
    vtype: "boolean"

- name: "admin pass"
  sudo: yes
  no_log: True
  debconf:
    name: "phpmyadmin"
    question: "phpmyadmin/mysql/admin-pass"
    value: "{{ phpmyadmin_mysql_admin_pass }}"
    vtype: "password"
  changed_when: false

- name: "app pass"
  sudo: yes
  no_log: True
  debconf:
    name: "phpmyadmin"
    question: "phpmyadmin/mysql/app-pass"
    value: "{{ phpmyadmin_mysql_app_pass }}"
    vtype: "password"
  changed_when: false

- name: "confirm pass"
  sudo: yes
  no_log: True
  debconf:
    name: "phpmyadmin"
    question: "phpmyadmin/app-password-confirm"
    value: "{{ phpmyadmin_mysql_app_pass }}"
    vtype: "password"
  changed_when: false

- name: "phpmyadmin apache"
  sudo: yes
  no_log: True
  debconf:
    name: "phpmyadmin"
    question: "phpmyadmin/reconfigure-webserver"
    value: "apache2"
    vtype: "multiselect"
  when: phpmyadmin_server == 'apache'

- name: "phpmyadmin nginx"
  sudo: yes
  no_log: True
  debconf:
    name: "phpmyadmin"
    question: "phpmyadmin/reconfigure-webserver"
    value: ""
    vtype: "multiselect"
  when: phpmyadmin_server == 'nginx'
