---
- name: "virtualhost config"
  sudo: yes
  template:
    src: "vhost.conf.j2"
    dest: "/etc/apache2/sites-available/phpmyadmin.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "phpmyadmin server restart"

- name: "virtualhost symlink"
  sudo: yes
  file:
    src: "/etc/apache2/sites-available/phpmyadmin.conf"
    dest: "/etc/apache2/sites-enabled/phpmyadmin.conf"
    state: link
    force: yes
  notify: "phpmyadmin server restart"
